version: '3.7'

services:

  caddy:
    container_name: caddy_web_server
    build:
      context: ./caddy_server
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy_server/Caddyfile:/etc/caddy/Caddyfile
      - ./backend/staticfiles:/var/www/html/static




volumes:
  static_volume:
