# Generated by Django 4.0.1 on 2022-02-04 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_transaction_rename_accounts_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='account',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
